### YamlMime:UniversalReference
ms.openlocfilehash: 22a643175009a3e2b6a48681140d1f1dbae34757
ms.sourcegitcommit: 87f95d58ec8de16e115bc344efeb084afc346b74
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 08/12/2018
ms.locfileid: "40074979"
items:
- uid: azure-event-hubs.ConditionErrorNameMapper
  name: ConditionErrorNameMapper
  fullName: ConditionErrorNameMapper
  children:
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:forced
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:timeout
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:redirect
  - azure-event-hubs.ConditionErrorNameMapper.amqp:decode-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:frame-size-too-small
  - azure-event-hubs.ConditionErrorNameMapper.amqp:illegal-state
  - azure-event-hubs.ConditionErrorNameMapper.amqp:internal-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:invalid-field
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:detach-forced
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:message-size-exceeded
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:redirect
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:stolen
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:transfer-limit-exceeded
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-allowed
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-found
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-implemented
  - azure-event-hubs.ConditionErrorNameMapper.amqp:precondition-failed
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-deleted
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:framing-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-locked
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:errant-link
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:handle-in-use
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:unattached-handle
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:window-violation
  - azure-event-hubs.ConditionErrorNameMapper.amqp:unauthorized-access
  - azure-event-hubs.ConditionErrorNameMapper.client.sender:not-enough-link-credit
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-error
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-out-of-range
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:auth-failed
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:entity-disabled
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:message-lock-lost
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:operation-cancelled
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:precondition-failed
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:server-busy
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-cannot-be-locked
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-lock-lost
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-limit-exceeded
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="51e30-101">Las condiciones se asigna a los nombres de Error.</span><span class="sxs-lookup"><span data-stu-id="51e30-101">Maps the conditions to the Error names.</span></span>
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:forced
  name: amqp:connection:forced
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-102">Error se produce cuando un operador intervenido para cerrar la conexión por alguna razón.</span><span class="sxs-lookup"><span data-stu-id="51e30-102">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:timeout
  name: com.microsoft:timeout
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-103">Error se produce cuando el servicio no está disponible.</span><span class="sxs-lookup"><span data-stu-id="51e30-103">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="51e30-104">Se debe reintentar la operación.</span><span class="sxs-lookup"><span data-stu-id="51e30-104">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:redirect
  name: amqp:connection:redirect
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-105">Error se produce cuando el contenedor ya no está disponible en la conexión actual.</span><span class="sxs-lookup"><span data-stu-id="51e30-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:decode-error
  name: amqp:decode-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-106">Error se produce cuando no se pudieron descodificar datos.</span><span class="sxs-lookup"><span data-stu-id="51e30-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:frame-size-too-small
  name: amqp:frame-size-too-small
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-107">Error se produce cuando el mismo nivel no puede enviar un marco porque la codificación más pequeño del performativo con los valores válidos actualmente sería demasiado grande para caber dentro de un marco del tamaño máximo de trama acordado.</span><span class="sxs-lookup"><span data-stu-id="51e30-107">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:illegal-state
  name: amqp:illegal-state
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-108">Error se produce cuando el mismo nivel envía un marco que no se permite en el estado actual.</span><span class="sxs-lookup"><span data-stu-id="51e30-108">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:internal-error
  name: amqp:internal-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-109">Error se produce cuando se produjo un error interno del servidor.</span><span class="sxs-lookup"><span data-stu-id="51e30-109">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="51e30-110">¿Es posible que haya encontrado un error?</span><span class="sxs-lookup"><span data-stu-id="51e30-110">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:invalid-field
  name: amqp:invalid-field
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-111">Error se produce cuando un campo no válido se pasó en el cuerpo de marco y la operación no se pudo continuar.</span><span class="sxs-lookup"><span data-stu-id="51e30-111">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:detach-forced
  name: amqp:link:detach-forced
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-112">Error se produce cuando un operador intervenido desasociar por algún motivo.</span><span class="sxs-lookup"><span data-stu-id="51e30-112">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:message-size-exceeded
  name: amqp:link:message-size-exceeded
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="51e30-113">Se produce un error cuando el mensaje enviado es demasiado grande: el tamaño máximo es 256Kb.</span><span class="sxs-lookup"><span data-stu-id="51e30-113">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:redirect
  name: amqp:link:redirect
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-114">Error se produce cuando la dirección proporcionada no se puede resolver para un término en el contenedor actual.</span><span class="sxs-lookup"><span data-stu-id="51e30-114">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:stolen
  name: amqp:link:stolen
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-115">Error se produce cuando dos o más instancias que se conectan a la misma partición con valores de tiempo diferentes.</span><span class="sxs-lookup"><span data-stu-id="51e30-115">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:transfer-limit-exceeded
  name: amqp:link:transfer-limit-exceeded
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-116">Error se produce cuando el mismo nivel envía más las transferencias de mensajes que actualmente está permitido en el vínculo.</span><span class="sxs-lookup"><span data-stu-id="51e30-116">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-allowed
  name: amqp:not-allowed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-117">Error se produce cuando se intenta realizar una operación, pero no se permite.</span><span class="sxs-lookup"><span data-stu-id="51e30-117">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-found
  name: amqp:not-found
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-118">Error en la señalización de errores de comunicación general relacionados con las operaciones de mensajería.</span><span class="sxs-lookup"><span data-stu-id="51e30-118">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-implemented
  name: amqp:not-implemented
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-119">Error se produce cuando una característica todavía no está implementada pero está presente el marcador de posición.</span><span class="sxs-lookup"><span data-stu-id="51e30-119">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:precondition-failed
  name: amqp:precondition-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-120">Error se produce cuando no es una condición que debe cumplir con el fin de ejecutar una operación.</span><span class="sxs-lookup"><span data-stu-id="51e30-120">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-deleted
  name: amqp:resource-deleted
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-121">Error se produce cuando el cliente está trabajando con una entidad del servidor se ha eliminado.</span><span class="sxs-lookup"><span data-stu-id="51e30-121">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:framing-error
  name: amqp:connection:framing-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-122">Error se produce cuando no se puede formar un encabezado de intervalo válido de la secuencia de bytes entrantes.</span><span class="sxs-lookup"><span data-stu-id="51e30-122">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-locked
  name: amqp:resource-locked
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-123">Error se produce cuando el cliente intenta trabajar con una entidad del servidor al que no tiene ningún acceso porque otro cliente que está trabajando con él.</span><span class="sxs-lookup"><span data-stu-id="51e30-123">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:errant-link
  name: amqp:session:errant-link
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-124">Error se produce cuando la entrada la recibió un vínculo que se ha separado con un error.</span><span class="sxs-lookup"><span data-stu-id="51e30-124">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:handle-in-use
  name: amqp:session:handle-in-use
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-125">Error se produce cuando se recibió una asociación con un identificador que ya está en uso para un vínculo conectado.</span><span class="sxs-lookup"><span data-stu-id="51e30-125">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:unattached-handle
  name: amqp:session:unattached-handle
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-126">Error se produce cuando se recibió un marco (distintos de adjuntar) que hacen referencia a un identificador que no está actualmente en uso de un vínculo conectado.</span><span class="sxs-lookup"><span data-stu-id="51e30-126">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:window-violation
  name: amqp:session:window-violation
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-127">Error se produce cuando el mismo nivel infringe ventana entrante para la sesión.</span><span class="sxs-lookup"><span data-stu-id="51e30-127">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:unauthorized-access
  name: amqp:unauthorized-access
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-128">Error se produce cuando los parámetros de conexión son incorrectas y el servidor rechazó la conexión.</span><span class="sxs-lookup"><span data-stu-id="51e30-128">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.client.sender:not-enough-link-credit
  name: client.sender:not-enough-link-credit
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-129">Error se produce cuando el remitente del cliente no tiene suficientes créditos del vínculo para enviar el mensaje.</span><span class="sxs-lookup"><span data-stu-id="51e30-129">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-error
  name: com.microsoft:argument-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-130">Error se produce cuando se recibió un argumento incorrecto.</span><span class="sxs-lookup"><span data-stu-id="51e30-130">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-out-of-range
  name: com.microsoft:argument-out-of-range
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-131">Error se produce cuando un argumento tiene un valor que está fuera del rango admisible.</span><span class="sxs-lookup"><span data-stu-id="51e30-131">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:auth-failed
  name: com.microsoft:auth-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-132">Error se produce cuando los parámetros de conexión son incorrectas y el servidor rechazó la conexión.</span><span class="sxs-lookup"><span data-stu-id="51e30-132">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:entity-disabled
  name: com.microsoft:entity-disabled
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-133">Error se produce cuando se intenta el acceso y conectarse a una entidad de mensajería deshabilitada.</span><span class="sxs-lookup"><span data-stu-id="51e30-133">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:message-lock-lost
  name: com.microsoft:message-lock-lost
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-134">Error se produce cuando el bloqueo del mensaje se pierde.</span><span class="sxs-lookup"><span data-stu-id="51e30-134">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:operation-cancelled
  name: com.microsoft:operation-cancelled
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-135">Error se produce cuando el servidor cancela la operación debido a un problema interno.</span><span class="sxs-lookup"><span data-stu-id="51e30-135">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:precondition-failed
  name: com.microsoft:precondition-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-136">Error se produce cuando no es una condición que debe cumplir con el fin de ejecutar una operación.</span><span class="sxs-lookup"><span data-stu-id="51e30-136">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:server-busy
  name: com.microsoft:server-busy
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-137">Error se produce cuando el servidor está ocupado.</span><span class="sxs-lookup"><span data-stu-id="51e30-137">Error is thrown when the server is busy.</span></span> <span data-ttu-id="51e30-138">Los llamadores deben espere unos instantes y vuelva a intentar la operación.</span><span class="sxs-lookup"><span data-stu-id="51e30-138">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-cannot-be-locked
  name: com.microsoft:session-cannot-be-locked
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-139">Error se produce cuando no se puede bloquear la sesión de bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="51e30-139">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-lock-lost
  name: com.microsoft:session-lock-lost
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="51e30-140">Error se produce cuando se pierde el bloqueo en la sesión de bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="51e30-140">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-limit-exceeded
  name: amqp:resource-limit-exceeded
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="51e30-141">Se produce el error la ha superado la cuota de centro de eventos y bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="51e30-141">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="51e30-142">Las cuotas se restablecen de forma periódica, esta operación tendrá que esperar hasta ese momento.</span><span class="sxs-lookup"><span data-stu-id="51e30-142">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="51e30-143">La entidad de mensajería alcanzó su tamaño máximo permitido.</span><span class="sxs-lookup"><span data-stu-id="51e30-143">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="51e30-144">Esto puede suceder si ya ha abierto el número máximo de destinatarios (que es 5) en un nivel de grupo por consumidor.</span><span class="sxs-lookup"><span data-stu-id="51e30-144">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
