### YamlMime:UniversalReference
ms.openlocfilehash: 6cb0f3f80bc511a0865f3a5609cf1784ff077b9b
ms.sourcegitcommit: 87f95d58ec8de16e115bc344efeb084afc346b74
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 08/12/2018
ms.locfileid: "40072991"
items:
- uid: azure-event-hubs.ErrorNameConditionMapper
  name: ErrorNameConditionMapper
  fullName: ErrorNameConditionMapper
  children:
  - azure-event-hubs.ErrorNameConditionMapper.ArgumentError
  - azure-event-hubs.ErrorNameConditionMapper.UnauthorizedError
  - azure-event-hubs.ErrorNameConditionMapper.ConnectionForcedError
  - azure-event-hubs.ErrorNameConditionMapper.ConnectionRedirectError
  - azure-event-hubs.ErrorNameConditionMapper.DecodeError
  - azure-event-hubs.ErrorNameConditionMapper.DetachForcedError
  - azure-event-hubs.ErrorNameConditionMapper.ErrantLinkError
  - azure-event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError
  - azure-event-hubs.ErrorNameConditionMapper.FramingError
  - azure-event-hubs.ErrorNameConditionMapper.HanldeInUseError
  - azure-event-hubs.ErrorNameConditionMapper.IllegalStateError
  - azure-event-hubs.ErrorNameConditionMapper.InternalServerError
  - azure-event-hubs.ErrorNameConditionMapper.InvalidFieldError
  - azure-event-hubs.ErrorNameConditionMapper.InvalidOperationError
  - azure-event-hubs.ErrorNameConditionMapper.LinkRedirectError
  - azure-event-hubs.ErrorNameConditionMapper.MessageLockLostError
  - azure-event-hubs.ErrorNameConditionMapper.MessageTooLargeError
  - azure-event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError
  - azure-event-hubs.ErrorNameConditionMapper.NotImplementedError
  - azure-event-hubs.ErrorNameConditionMapper.OperationCancelledError
  - azure-event-hubs.ErrorNameConditionMapper.PreconditionFailedError
  - azure-event-hubs.ErrorNameConditionMapper.QuotaExceededError
  - azure-event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError
  - azure-event-hubs.ErrorNameConditionMapper.ResourceDeletedError
  - azure-event-hubs.ErrorNameConditionMapper.ResourceLockedError
  - azure-event-hubs.ErrorNameConditionMapper.SenderBusyError
  - azure-event-hubs.ErrorNameConditionMapper.ServerBusyError
  - azure-event-hubs.ErrorNameConditionMapper.ServiceCommunicationError
  - azure-event-hubs.ErrorNameConditionMapper.ServiceUnavailableError
  - azure-event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError
  - azure-event-hubs.ErrorNameConditionMapper.SessionLockLostError
  - azure-event-hubs.ErrorNameConditionMapper.SessionWindowViolationError
  - azure-event-hubs.ErrorNameConditionMapper.TransferLimitExceededError
  - azure-event-hubs.ErrorNameConditionMapper.UnattachedHandleError
  - azure-event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="9b2be-101">Las condiciones se asigna a los nombres de Error.</span><span class="sxs-lookup"><span data-stu-id="9b2be-101">Maps the conditions to the Error names.</span></span>
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ArgumentError
  name: ArgumentError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-102">Error se produce cuando se recibió un argumento incorrecto.</span><span class="sxs-lookup"><span data-stu-id="9b2be-102">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.UnauthorizedError
  name: UnauthorizedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-103">Error se produce cuando los parámetros de conexión son incorrectas y el servidor rechazó la conexión.</span><span class="sxs-lookup"><span data-stu-id="9b2be-103">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ConnectionForcedError
  name: ConnectionForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-104">Error se produce cuando un operador intervenido para cerrar la conexión por alguna razón.</span><span class="sxs-lookup"><span data-stu-id="9b2be-104">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ConnectionRedirectError
  name: ConnectionRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-105">Error se produce cuando el contenedor ya no está disponible en la conexión actual.</span><span class="sxs-lookup"><span data-stu-id="9b2be-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.DecodeError
  name: DecodeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-106">Error se produce cuando no se pudieron descodificar datos.</span><span class="sxs-lookup"><span data-stu-id="9b2be-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.DetachForcedError
  name: DetachForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-107">Error se produce cuando un operador intervenido desasociar por algún motivo.</span><span class="sxs-lookup"><span data-stu-id="9b2be-107">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ErrantLinkError
  name: ErrantLinkError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-108">Error se produce cuando la entrada la recibió un vínculo que se ha separado con un error.</span><span class="sxs-lookup"><span data-stu-id="9b2be-108">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError
  name: FrameSizeTooSmallError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-109">Error se produce cuando el mismo nivel no puede enviar un marco porque la codificación más pequeño del performativo con los valores válidos actualmente sería demasiado grande para caber dentro de un marco del tamaño máximo de trama acordado.</span><span class="sxs-lookup"><span data-stu-id="9b2be-109">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.FramingError
  name: FramingError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-110">Error se produce cuando no se puede formar un encabezado de intervalo válido de la secuencia de bytes entrantes.</span><span class="sxs-lookup"><span data-stu-id="9b2be-110">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.HanldeInUseError
  name: HanldeInUseError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-111">Error se produce cuando se recibió una asociación con un identificador que ya está en uso para un vínculo conectado.</span><span class="sxs-lookup"><span data-stu-id="9b2be-111">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.IllegalStateError
  name: IllegalStateError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-112">Error se produce cuando el mismo nivel envía un marco que no se permite en el estado actual.</span><span class="sxs-lookup"><span data-stu-id="9b2be-112">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InternalServerError
  name: InternalServerError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-113">Error se produce cuando se produjo un error interno del servidor.</span><span class="sxs-lookup"><span data-stu-id="9b2be-113">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="9b2be-114">¿Es posible que haya encontrado un error?</span><span class="sxs-lookup"><span data-stu-id="9b2be-114">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InvalidFieldError
  name: InvalidFieldError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-115">Error se produce cuando un campo no válido se pasó en el cuerpo de marco y la operación no se pudo continuar.</span><span class="sxs-lookup"><span data-stu-id="9b2be-115">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InvalidOperationError
  name: InvalidOperationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-116">Error se produce cuando se intenta realizar una operación, pero no se permite.</span><span class="sxs-lookup"><span data-stu-id="9b2be-116">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.LinkRedirectError
  name: LinkRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-117">Error se produce cuando la dirección proporcionada no se puede resolver para un término en el contenedor actual.</span><span class="sxs-lookup"><span data-stu-id="9b2be-117">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessageLockLostError
  name: MessageLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-118">Error se produce cuando el bloqueo del mensaje se pierde.</span><span class="sxs-lookup"><span data-stu-id="9b2be-118">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessageTooLargeError
  name: MessageTooLargeError
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="9b2be-119">Se produce un error cuando el mensaje enviado es demasiado grande: el tamaño máximo es 256Kb.</span><span class="sxs-lookup"><span data-stu-id="9b2be-119">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError
  name: ArgumentOutOfRangeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-120">Error se produce cuando un argumento tiene un valor que está fuera del rango admisible.</span><span class="sxs-lookup"><span data-stu-id="9b2be-120">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.NotImplementedError
  name: NotImplementedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-121">Error se produce cuando una característica todavía no está implementada pero está presente el marcador de posición.</span><span class="sxs-lookup"><span data-stu-id="9b2be-121">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.OperationCancelledError
  name: OperationCancelledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-122">Error se produce cuando el servidor cancela la operación debido a un problema interno.</span><span class="sxs-lookup"><span data-stu-id="9b2be-122">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.PreconditionFailedError
  name: PreconditionFailedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-123">Error se produce cuando no es una condición que debe cumplir con el fin de ejecutar una operación.</span><span class="sxs-lookup"><span data-stu-id="9b2be-123">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.QuotaExceededError
  name: QuotaExceededError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="9b2be-124">Se produce el error la ha superado la cuota de centro de eventos y bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="9b2be-124">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="9b2be-125">Las cuotas se restablecen de forma periódica, esta operación tendrá que esperar hasta ese momento.</span><span class="sxs-lookup"><span data-stu-id="9b2be-125">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="9b2be-126">La entidad de mensajería alcanzó su tamaño máximo permitido.</span><span class="sxs-lookup"><span data-stu-id="9b2be-126">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="9b2be-127">Esto puede suceder si ya ha abierto el número máximo de destinatarios (que es 5) en un nivel de grupo por consumidor.</span><span class="sxs-lookup"><span data-stu-id="9b2be-127">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError
  name: ReceiverDisconnectedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-128">Error se produce cuando dos o más instancias que se conectan a la misma partición con valores de tiempo diferentes.</span><span class="sxs-lookup"><span data-stu-id="9b2be-128">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ResourceDeletedError
  name: ResourceDeletedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-129">Error se produce cuando el cliente está trabajando con una entidad del servidor se ha eliminado.</span><span class="sxs-lookup"><span data-stu-id="9b2be-129">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ResourceLockedError
  name: ResourceLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-130">Error se produce cuando el cliente intenta trabajar con una entidad del servidor al que no tiene ningún acceso porque otro cliente que está trabajando con él.</span><span class="sxs-lookup"><span data-stu-id="9b2be-130">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SenderBusyError
  name: SenderBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-131">Error se produce cuando el remitente del cliente no tiene suficientes créditos del vínculo para enviar el mensaje.</span><span class="sxs-lookup"><span data-stu-id="9b2be-131">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServerBusyError
  name: ServerBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-132">Error se produce cuando el servidor está ocupado.</span><span class="sxs-lookup"><span data-stu-id="9b2be-132">Error is thrown when the server is busy.</span></span> <span data-ttu-id="9b2be-133">Los llamadores deben espere unos instantes y vuelva a intentar la operación.</span><span class="sxs-lookup"><span data-stu-id="9b2be-133">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServiceCommunicationError
  name: ServiceCommunicationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-134">Error en la señalización de errores de comunicación general relacionados con las operaciones de mensajería.</span><span class="sxs-lookup"><span data-stu-id="9b2be-134">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServiceUnavailableError
  name: ServiceUnavailableError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-135">Error se produce cuando el servicio no está disponible.</span><span class="sxs-lookup"><span data-stu-id="9b2be-135">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="9b2be-136">Se debe reintentar la operación.</span><span class="sxs-lookup"><span data-stu-id="9b2be-136">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError
  name: SessionCannotBeLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-137">Error se produce cuando no se puede bloquear la sesión de bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="9b2be-137">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionLockLostError
  name: SessionLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-138">Error se produce cuando se pierde el bloqueo en la sesión de bus de servicio de Azure.</span><span class="sxs-lookup"><span data-stu-id="9b2be-138">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionWindowViolationError
  name: SessionWindowViolationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-139">Error se produce cuando el mismo nivel infringe ventana entrante para la sesión.</span><span class="sxs-lookup"><span data-stu-id="9b2be-139">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.TransferLimitExceededError
  name: TransferLimitExceededError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-140">Error se produce cuando el mismo nivel envía más las transferencias de mensajes que actualmente está permitido en el vínculo.</span><span class="sxs-lookup"><span data-stu-id="9b2be-140">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.UnattachedHandleError
  name: UnattachedHandleError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-141">Error se produce cuando se recibió un marco (distintos de adjuntar) que hacen referencia a un identificador que no está actualmente en uso de un vínculo conectado.</span><span class="sxs-lookup"><span data-stu-id="9b2be-141">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError
  name: MessagingEntityDisabledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="9b2be-142">Error se produce cuando se intenta el acceso y conectarse a una entidad de mensajería deshabilitada.</span><span class="sxs-lookup"><span data-stu-id="9b2be-142">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
